# Generated by Django 5.0.7 on 2024-09-27 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('menu_name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('file_name', models.CharField(max_length=100)),
                ('icon_path', models.CharField(max_length=100)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('row_index', models.IntegerField(blank=True, null=True)),
                ('is_module', models.BooleanField(default=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('is_administrator', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('user_name', models.CharField(blank=True, max_length=100, null=True)),
                ('display_name', models.CharField(blank=True, error_messages={'unique': 'Username already exists'}, max_length=100, null=True, unique=True)),
                ('mobile_number', models.CharField(blank=True, max_length=10, null=True)),
                ('email_id', models.EmailField(max_length=254, null=True, unique=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='user/profile/')),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('mobile_verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('otp', models.CharField(max_length=250, null=True)),
                ('otp_expiry_datetime', models.DateTimeField(blank=True, null=True)),
                ('otp_expired', models.BooleanField(blank=True, default=False, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('account_holder_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_no', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=30, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=200, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=200, null=True)),
                ('dateOf_birth', models.DateField(blank=True, null=True)),
                ('is_super_admin', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usercreate_user_id', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userupdate_user_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlockedToken',
            fields=[
                ('token_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_block_token', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('category_desc', models.TextField(blank=True, null=True)),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='category')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='cat_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='cat_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=100)),
                ('brand_image', models.ImageField(blank=True, null=True, upload_to='brand/brandImage/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='brand_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='brand_updated_by', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='brand_category_id', to='flourishapi.category')),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('log_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('transaction_name', models.CharField(max_length=250)),
                ('mode', models.CharField(max_length=100)),
                ('log_message', models.TextField()),
                ('Ip_address', models.CharField(blank=True, max_length=100, null=True)),
                ('system_name', models.CharField(blank=True, max_length=100, null=True)),
                ('log_date', models.DateTimeField()),
                ('log_type', models.IntegerField(default=1)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('role_permission_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='role_permission_menu_id', to='flourishapi.menu')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('unit_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('unit_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='unit_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='unit_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product/productImage/')),
                ('mrp', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('customer_price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('desc', models.TextField(blank=True, null=True)),
                ('sales_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='product_brand_id', to='flourishapi.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='product_category_id', to='flourishapi.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='product_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='product_updated_by', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='product_unit_id', to='flourishapi.unit')),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('usergroup_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('usergroup_name', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='usergroup_created_id', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='usergroup_updated_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='usergroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='user_group_id', to='flourishapi.usergroup'),
        ),
        migrations.CreateModel(
            name='UserGroupMenu',
            fields=[
                ('usergroup_menu_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='menuid', to='flourishapi.menu')),
                ('usergroup', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='usergroupid', to='flourishapi.usergroup')),
            ],
        ),
    ]
