# Generated by Django 5.0.7 on 2024-10-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flourishapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(blank=True, error_messages={'unique': 'Username already exists'}, max_length=100, null=True, unique=True),
        ),
    ]
