# Generated by Django 5.0.7 on 2024-10-02 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flourishapi', '0002_alter_user_display_name_alter_user_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='username',
        ),
    ]
