# Generated by Django 5.1.1 on 2024-10-04 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flourishapi', '0005_rename_category_category_categoryid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_id',
            new_name='email',
        ),
    ]
