# Generated by Django 5.1.1 on 2024-10-11 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flourishapi', '0006_rename_email_id_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('emailsettings_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('host', models.CharField(blank=True, max_length=50, null=True)),
                ('port', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('admin_settingsid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('otp_length', models.IntegerField(default=0)),
                ('otp_expiry_duration', models.IntegerField(default=0)),
                ('is_maintenance_mode', models.BooleanField(default=False)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_contact_no', models.CharField(blank=True, max_length=20, null=True)),
                ('company_email', models.EmailField(max_length=254, null=True, unique=True)),
                ('company_address', models.CharField(blank=True, max_length=255, null=True)),
                ('company_desc', models.TextField(blank=True, null=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company/company_logos/')),
                ('stock_update_at', models.DateTimeField(blank=True, null=True)),
                ('is_stock', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_config_userid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BillnoSettings',
            fields=[
                ('billno_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('employee_prefix', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_length', models.IntegerField(default=0)),
                ('employee_live', models.IntegerField(default=0)),
                ('bat_prefix', models.CharField(blank=True, max_length=50, null=True)),
                ('bat_length', models.IntegerField(blank=True, default=0, null=True)),
                ('bat_live', models.IntegerField(blank=True, default=0, null=True)),
                ('inv_prefix', models.CharField(blank=True, max_length=100, null=True)),
                ('inv_length', models.IntegerField(default=0)),
                ('inv_live', models.IntegerField(default=0)),
                ('pur_prefix', models.CharField(blank=True, max_length=100, null=True)),
                ('pur_length', models.IntegerField(default=0)),
                ('pur_live', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='billnosetting_userid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
