# Generated by Django 5.1.1 on 2024-10-16 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flourishapi', '0007_emailsettings_alter_usergroup_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock',
            fields=[
                ('stock_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('batch_no', models.CharField(max_length=100)),
                ('expire_date', models.DateField()),
                ('sales_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('unit_sales_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('stock_qty', models.IntegerField()),
                ('total_qty', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='stockproductid', to='flourishapi.product')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stockunitid', to='flourishapi.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Opening',
            fields=[
                ('opening_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('convertion_value', models.IntegerField(default=1)),
                ('batch_no', models.CharField(max_length=100)),
                ('expire_date', models.DateField()),
                ('total_qty', models.IntegerField()),
                ('sales_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='openstockcreatedby', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='openstockproductid', to='flourishapi.product')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='openunitid', to='flourishapi.unit')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='openstockeditedby', to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='openstockstockid', to='flourishapi.stock')),
            ],
        ),
    ]
