# Generated by Django 5.1.1 on 2024-10-17 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flourishapi', '0008_stock_opening'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='convertion_value',
            field=models.IntegerField(default=1),
        ),
    ]
