# Generated by Django 5.1.1 on 2024-10-17 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flourishapi', '0009_unit_convertion_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillType',
            fields=[
                ('bill_typeid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('bill_type', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransPurchase',
            fields=[
                ('purchase_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('bill_no', models.CharField(max_length=100)),
                ('bill_date', models.DateField()),
                ('due_date', models.DateField()),
                ('purchase_no', models.CharField(blank=True, max_length=200, null=True)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('round_off', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('balanceAmount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('is_locked', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('bill_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tpbilltypeid', to='flourishapi.billtype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tpcreatedby', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tpeditedby', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
