# Generated by Django 5.1.1 on 2024-10-18 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flourishapi', '0010_billtype_transpurchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchase_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('purchase_no', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_date', models.DateTimeField(blank=True, null=True)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('round_off', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('is_locked', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('bill_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tpbilltypeid', to='flourishapi.billtype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tpcreatedby', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tpeditedby', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseDet',
            fields=[
                ('purchasedet_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('convertionValue', models.IntegerField(default=1)),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('batch_no', models.CharField(max_length=100)),
                ('qty', models.IntegerField()),
                ('mrp_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('sales_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tpditemid', to='flourishapi.product')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='tpdpurchaseid', to='flourishapi.purchase')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='trpurchasedetstockid', to='flourishapi.stock')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tpdunitid', to='flourishapi.unit')),
            ],
        ),
        migrations.DeleteModel(
            name='TransPurchase',
        ),
    ]
