# Generated by Django 5.1.1 on 2024-10-18 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flourishapi', '0011_purchase_purchasedet_delete_transpurchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='remarks',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='purchasedet',
            old_name='convertionValue',
            new_name='convertion_value',
        ),
    ]
