# Generated by Django 5.1.1 on 2024-10-21 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flourishapi', '0012_rename_remarks_purchase_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='pos_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='opening',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='POS',
            fields=[
                ('pos_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('pos_no', models.CharField(blank=True, max_length=100, null=True)),
                ('pos_date', models.DateTimeField(blank=True, null=True)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('round_off', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('notes', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('bill_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tposbilltypeid', to='flourishapi.billtype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tposcreatedby', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tposeditedby', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PosDet',
            fields=[
                ('purchasedet_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('actual_wgt', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('avg_wgt', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tpdcategoryid', to='flourishapi.category')),
                ('pos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='tpdposid', to='flourishapi.pos')),
            ],
        ),
    ]
