# Generated by Django 5.1.1 on 2024-10-21 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flourishapi', '0013_adminsettings_pos_amount_alter_opening_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posdet',
            old_name='price',
            new_name='total_amount',
        ),
    ]
