# Generated by Django 5.1.1 on 2024-10-24 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flourishapi', '0014_rename_price_posdet_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opening',
            name='product',
        ),
        migrations.AddField(
            model_name='opening',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='openstockproductid', to='flourishapi.product'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('doj', models.DateTimeField(blank=True, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('employee_image', models.ImageField(blank=True, null=True, upload_to='employee/employeeImage/')),
                ('adddress', models.TextField(blank=True, null=True)),
                ('username', models.CharField(blank=True, error_messages={'unique': 'Username already exists'}, max_length=100, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='employee_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='employee_updated_by', to=settings.AUTH_USER_MODEL)),
                ('usergroup', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='employee_usergroupid', to='flourishapi.usergroup')),
            ],
        ),
    ]
