# Generated by Django 5.1.1 on 2024-10-24 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flourishapi', '0015_remove_opening_product_opening_employee_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opening',
            old_name='employee',
            new_name='product',
        ),
    ]
