# Generated by Django 5.1.1 on 2024-10-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flourishapi', '0016_rename_employee_opening_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='adddress',
            new_name='address',
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
