# Generated by Django 5.1.1 on 2024-10-25 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flourishapi', '0017_rename_adddress_employee_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='employee_userid', to=settings.AUTH_USER_MODEL),
        ),
    ]
