# Generated by Django 5.1.1 on 2024-10-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flourishapi', '0018_employee_emp_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='doj',
            field=models.DateField(blank=True, null=True),
        ),
    ]
