# Generated by Django 5.1.1 on 2024-10-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flourishapi', '0021_stock_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='log_type',
            field=models.CharField(max_length=100),
        ),
    ]
