# Generated by Django 5.1.1 on 2024-10-28 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flourishapi', '0022_alter_logs_log_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='usergroup_created_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
